// AUTO-GENERATED by gen_specialized.py from scu_dsp_capture_06.bin
// DO NOT EDIT BY HAND - regenerate from the capture instead.
//
// One switch case per ProgramRam address, valid ONLY when the currently
// loaded program matches GRANDIA_DSP_PROGRAM_HASH. Each function reproduces
// exactly what the interpreter's Operation Command / Load Immediate Command
// switch would do for that address's known, fixed instruction word - with
// all bitfield decoding resolved at generation time instead of at runtime.
//
// DMA / Jump / Other commands are intentionally NOT specialized here.
// The generated macro jumps directly to the common instruction epilogue
// for specialized addresses; other addresses fall back to the interpreter.

#define SCU_DSP_SPECIALIZED_GRANDIA_STEP() do { \
   switch (ScuDsp->PC) { \
   case 0x00: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0xE); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x01: { \
      writeloadimdest_specialized(0x0, (u32)0x00000001); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x02: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x03: { \
      writed1busdest_specialized(0x7, readgensrc_specialized(0x4)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x04: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x1); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x05: { \
      writed1busdest_specialized(0x6, readgensrc_specialized(0x4)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x06: { \
      writed1busdest_specialized(0xE, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x08: { \
      writed1busdest_specialized(0x6, readgensrc_specialized(0x4)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x09: { \
      writed1busdest_specialized(0xF, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x0B: { \
      writed1busdest_specialized(0x6, readgensrc_specialized(0x4)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x0C: { \
      writed1busdest_specialized(0xD, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x0E: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0xE); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x0F: { \
      ScuDsp->RY = readgensrc_specialized(0x0); \
      writed1busdest_specialized(0xD, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x10: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x10); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x11: { \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      writed1busdest_specialized(0xB, (u32)(signed char)0x13); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x12: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->AC.all = 0; \
      writed1busdest_specialized(0xA, (u32)(signed char)0x3); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x13: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x14: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x15: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x16: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x17: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x18: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x19: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x1A: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x1B: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x1C: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x1D: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x1E: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x1F: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x20: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x21: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x22: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x23: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x24: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x25: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x26: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x27: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x28: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x29: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x2A: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      writed1busdest_specialized(0xE, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x2C: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x2D: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x2E: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x2F: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x30: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      writed1busdest_specialized(0xA, (u32)(signed char)0x2B); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x31: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x32: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x33: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0xF, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x34: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x35: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      writed1busdest_specialized(0xB, (u32)(signed char)0x3E); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x36: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x37: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x10); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x38: { \
      writed1busdest_specialized(0xD, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x39: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x4); \
      writed1busdest_specialized(0x5, (u32)(signed char)0x7C); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x3B: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x4); \
      writed1busdest_specialized(0x1, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x3C: { \
      writed1busdest_specialized(0xA, (u32)(signed char)0x15); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x3D: { \
      writed1busdest_specialized(0xD, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x3E: { \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x2); \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x1); \
      writed1busdest_specialized(0x4, (u32)(signed char)0xFE); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x3F: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x3); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0xC, (u32)(signed char)0xA); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x40: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->RY = readgensrc_specialized(0x2); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x5, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x41: { \
      if (!ScuDsp->ProgControlPort.part.S) writeloadimdest_specialized(0x5, (u32)0x000000FF); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x42: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s64)((u32)ScuDsp->AC.part.L & (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x1); \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x43: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->RY = readgensrc_specialized(0x3); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x5, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x44: { \
      if (!ScuDsp->ProgControlPort.part.S) writeloadimdest_specialized(0x5, (u32)0x000000FF); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x45: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s64)((u32)ScuDsp->AC.part.L & (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x1); \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x46: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x5, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x47: { \
      if (!ScuDsp->ProgControlPort.part.S) writeloadimdest_specialized(0x5, (u32)0x000000FF); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x48: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s64)((u32)ScuDsp->AC.part.L & (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0xC, (u32)(signed char)0xA); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x49: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x4); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x4A: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (u64)((u32)ScuDsp->AC.part.L | (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x4B: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x4); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x4C: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (u64)((u32)ScuDsp->AC.part.L | (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x1, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x4D: { \
      writeloadimdest_specialized(0x5, (u32)0x00FF00FF); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x4E: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s64)((u32)ScuDsp->AC.part.L & (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x6); \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x1); \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x4F: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x7); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0xC, (u32)(signed char)0xC); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x50: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x5, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x51: { \
      if (!ScuDsp->ProgControlPort.part.S) writeloadimdest_specialized(0x5, (u32)0x000000FF); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x52: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s64)((u32)ScuDsp->AC.part.L & (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x53: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x4); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x55: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (u64)((u32)ScuDsp->AC.part.L | (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      writed1busdest_specialized(0x1, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x56: { \
      writed1busdest_specialized(0xD, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x58: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x59: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      writed1busdest_specialized(0xD, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x5A: { \
      writeloadimdest_specialized(0x5, (u32)0x00000160); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x5B: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x7, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x5C: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x3); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x5D: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x5E: { \
      writeloadimdest_specialized(0x5, (u32)0x000000B0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x5F: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x6, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x60: { \
      writed1busdest_specialized(0xD, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x62: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0xE); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x63: { \
      ScuDsp->RY = readgensrc_specialized(0x0); \
      writed1busdest_specialized(0xD, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x64: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x10); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x65: { \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      writed1busdest_specialized(0xB, (u32)(signed char)0x67); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x66: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->AC.all = 0; \
      writed1busdest_specialized(0xA, (u32)(signed char)0x3); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x67: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x68: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x69: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x6A: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x6B: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x6C: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x6D: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x6E: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x6F: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x70: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x71: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x72: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x73: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x74: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x75: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x76: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x77: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x78: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x79: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x7A: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x7B: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x7C: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x7D: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x7E: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      writed1busdest_specialized(0xE, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x80: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x81: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x82: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0xB, (u32)(signed char)0x92); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x83: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x84: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      writed1busdest_specialized(0xA, (u32)(signed char)0x2B); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x85: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x86: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x87: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0xF, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x88: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      writed1busdest_specialized(0x4, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x89: { \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->RX = readgensrc_specialized(0x5); \
      ScuDsp->AC.all = 0; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x8A: { \
      ScuDsp->ALU.all = (s64)ScuDsp->AC.all + (s64)ScuDsp->P.all; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.all == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.all & 0x800000000000) != 0); \
      ScuDsp->ProgControlPort.part.C = ((((ScuDsp->AC.all & 0xffffffffffff) + (ScuDsp->P.all & 0xffffffffffff)) & (0x1000000000000)) != 0); \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0xA)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x8B: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x10); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x8C: { \
      writed1busdest_specialized(0xD, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x8D: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x4); \
      writed1busdest_specialized(0x5, (u32)(signed char)0x7C); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x8F: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x4); \
      writed1busdest_specialized(0x1, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x90: { \
      writed1busdest_specialized(0xA, (u32)(signed char)0x15); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x91: { \
      writed1busdest_specialized(0xD, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x92: { \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x2); \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x1); \
      writed1busdest_specialized(0x4, (u32)(signed char)0xFE); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x93: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x3); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0xC, (u32)(signed char)0xA); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x94: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->RY = readgensrc_specialized(0x2); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x5, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x95: { \
      if (!ScuDsp->ProgControlPort.part.S) writeloadimdest_specialized(0x5, (u32)0x000000FF); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x96: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s64)((u32)ScuDsp->AC.part.L & (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x1); \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x97: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->RY = readgensrc_specialized(0x3); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x5, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x98: { \
      if (!ScuDsp->ProgControlPort.part.S) writeloadimdest_specialized(0x5, (u32)0x000000FF); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x99: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s64)((u32)ScuDsp->AC.part.L & (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->P.all = (s64)ScuDsp->RX * (s32)ScuDsp->RY; \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x1); \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x9A: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x5, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x9B: { \
      if (!ScuDsp->ProgControlPort.part.S) writeloadimdest_specialized(0x5, (u32)0x000000FF); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x9C: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s64)((u32)ScuDsp->AC.part.L & (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0xC, (u32)(signed char)0xA); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x9D: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x4); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x9E: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (u64)((u32)ScuDsp->AC.part.L | (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0x9F: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x4); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xA0: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (u64)((u32)ScuDsp->AC.part.L | (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x1, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xA1: { \
      writeloadimdest_specialized(0x5, (u32)0x00FF00FF); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xA2: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s64)((u32)ScuDsp->AC.part.L & (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x6); \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x1); \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xA3: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x7); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0xC, (u32)(signed char)0xC); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xA4: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      writed1busdest_specialized(0x5, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xA5: { \
      if (!ScuDsp->ProgControlPort.part.S) writeloadimdest_specialized(0x5, (u32)0x000000FF); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xA6: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s64)((u32)ScuDsp->AC.part.L & (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xA7: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ProgControlPort.part.C = (ScuDsp->AC.part.L >> 24) & 0x01; \
      ScuDsp->ALU.part.L = ((u32)(ScuDsp->AC.part.L << 8) | ((ScuDsp->AC.part.L >> 24) & 0xFF)); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((ScuDsp->ALU.part.L & 0x80000000) != 0); \
      ScuDsp->P.all = (s64)(s32)readgensrc_specialized(0x4); \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xA9: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (u64)((u32)ScuDsp->AC.part.L | (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      writed1busdest_specialized(0x1, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xAA: { \
      writed1busdest_specialized(0xD, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xAC: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xAD: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      writed1busdest_specialized(0x5, (u32)(signed char)0x2C); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xAE: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      writed1busdest_specialized(0x7, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xAF: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xB0: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      writed1busdest_specialized(0x5, (u32)(signed char)0x16); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xB1: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xB2: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xB3: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xB4: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      writed1busdest_specialized(0x5, (u32)(signed char)0x16); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xB5: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xB6: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      writed1busdest_specialized(0x5, (u32)(signed char)0x1); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xB7: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L - (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->AC.part.L - (u64)(u32)ScuDsp->P.part.L)) & 0x100000000) != 0; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xB9: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xBA: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xBB: { \
      writeloadimdest_specialized(0x5, (u32)0x00000160); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xBC: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      writed1busdest_specialized(0x7, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xBD: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xBE: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x3); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xBF: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xC0: { \
      writeloadimdest_specialized(0x5, (u32)0x000000B0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xC1: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L + (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s32)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->P.part.L + (u64)(u32)ScuDsp->AC.part.L) & 0x100000000) != 0); \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xC2: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x4); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xC3: { \
      writed1busdest_specialized(0x0, (u32)(signed char)0x8); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xC4: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      writed1busdest_specialized(0x5, (u32)(signed char)0x1); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xC5: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L - (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->AC.part.L - (u64)(u32)ScuDsp->P.part.L)) & 0x100000000) != 0; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xC7: { \
      /* NOP */ \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xC9: { \
      /* NOP */ \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xCA: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x6); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xCB: { \
      writed1busdest_specialized(0x7, readgensrc_specialized(0x4)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xCC: { \
      writed1busdest_specialized(0x6, readgensrc_specialized(0x4)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xCD: { \
      writed1busdest_specialized(0xB, (u32)(signed char)0xCF); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xCE: { \
      writed1busdest_specialized(0xA, (u32)(signed char)0x7); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xCF: { \
      writed1busdest_specialized(0xE, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xD1: { \
      /* NOP */ \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xD2: { \
      writed1busdest_specialized(0xE, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xD4: { \
      /* NOP */ \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xD6: { \
      /* NOP */ \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xD7: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x8); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xD8: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      writed1busdest_specialized(0x5, (u32)(signed char)0x1); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xD9: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L - (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->AC.part.L - (u64)(u32)ScuDsp->P.part.L)) & 0x100000000) != 0; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xDB: { \
      /* NOP */ \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xDD: { \
      /* NOP */ \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xDE: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x6); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xDF: { \
      writed1busdest_specialized(0x7, readgensrc_specialized(0x4)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xE0: { \
      writed1busdest_specialized(0x6, readgensrc_specialized(0x4)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xE1: { \
      writed1busdest_specialized(0xB, (u32)(signed char)0xE3); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xE2: { \
      writed1busdest_specialized(0xA, (u32)(signed char)0x7); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xE3: { \
      writed1busdest_specialized(0xE, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xE5: { \
      writed1busdest_specialized(0xE, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xE8: { \
      /* NOP */ \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xE9: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x8); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xEA: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      writed1busdest_specialized(0x5, (u32)(signed char)0x1); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xEB: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L - (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->AC.part.L - (u64)(u32)ScuDsp->P.part.L)) & 0x100000000) != 0; \
      writed1busdest_specialized(0x0, readgensrc_specialized(0x9)); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xED: { \
      writed1busdest_specialized(0xC, (u32)(signed char)0x6); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xEE: { \
      ScuDsp->AC.all = (s64)(s32)readgensrc_specialized(0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xEF: { \
      writeloadimdest_specialized(0x5, (u32)0x0003FFFF); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xF0: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s64)((u32)ScuDsp->AC.part.L & (u32)ScuDsp->P.part.L); \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = 0; \
      ScuDsp->AC.all = ScuDsp->ALU.all; \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xF1: { \
      writeloadimdest_specialized(0x5, (u32)0x00015C00); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xF2: { \
      ScuDsp->ALU.all = ScuDsp->AC.all; \
      ScuDsp->ALU.part.L = (s32)ScuDsp->AC.part.L - (s32)ScuDsp->P.part.L; \
      ScuDsp->ProgControlPort.part.Z = (ScuDsp->ALU.part.L == 0); \
      ScuDsp->ProgControlPort.part.S = ((s64)ScuDsp->ALU.part.L < 0); \
      ScuDsp->ProgControlPort.part.C = ((((u64)(u32)ScuDsp->AC.part.L - (u64)(u32)ScuDsp->P.part.L)) & 0x100000000) != 0; \
      writed1busdest_specialized(0xE, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xF4: { \
      /* NOP */ \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xF5: { \
      writeloadimdest_specialized(0x6, (u32)0xFF695C00); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xF7: { \
      writeloadimdest_specialized(0x7, (u32)0xFF69D400); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xF8: { \
      writed1busdest_specialized(0xE, (u32)(signed char)0x0); \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xFA: { \
      /* NOP */ \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xFC: { \
      /* NOP */ \
      goto scu_dsp_instruction_complete; \
   } \
   case 0xFD: { \
      /* NOP */ \
      goto scu_dsp_instruction_complete; \
   } \
   default: break; \
   } \
} while (0)
